# Generated by Django 5.1 on 2024-08-20 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0008_alter_driver_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='driver_files/')),
                ('part', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drivers.driver')),
            ],
        ),
    ]
