# Generated by Django 5.1 on 2024-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverfile',
            old_name='file_type',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='driverfile',
            old_name='file',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='driverfile',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='driverfile',
            name='part',
        ),
        migrations.RemoveField(
            model_name='driverfile',
            name='pending',
        ),
        migrations.AddField(
            model_name='driverfile',
            name='is_approvedby',
            field=models.CharField(default='Administrator'),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
