# Generated by Django 5.1 on 2024-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0002_rename_file_type_driverfile_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driverfile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
