# Generated by Django 5.1 on 2024-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0003_driverfile_created_at_driverfile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfile',
            name='file_type',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
