# Generated by Django 5.1 on 2024-08-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0004_driverfile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverfile',
            name='is_approvedby',
        ),
    ]
