# Generated by Django 5.1 on 2024-08-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0006_driverfile_is_approvedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverfile',
            old_name='is_approvedby',
            new_name='user',
        ),
    ]
