# Generated by Django 5.1 on 2024-08-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0007_rename_is_approvedby_driverfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverfile',
            name='user',
        ),
    ]
