# Generated by Django 5.1 on 2024-08-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverFlies', '0008_remove_driverfile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverfile',
            old_name='file_path',
            new_name='file',
        ),
    ]
