# Generated by Django 5.1 on 2024-08-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='delete_users',
            new_name='delete_admin',
        ),
    ]
