# Generated by Django 5.1 on 2024-08-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_delete_users_admin_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
