# Generated by Django 5.1 on 2024-09-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_is_createby_driver_is_updateby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driven_license_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
