# Generated by Django 5.1 on 2024-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_createby',
            field=models.CharField(default=False),
        ),
    ]
