# Generated by Django 5.1 on 2024-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_passenger_is_createby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='is_createby',
            field=models.CharField(),
        ),
    ]
