# Generated by Django 5.1 on 2024-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_alter_passenger_is_createby'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_updateby',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='is_createby',
            field=models.CharField(default=False),
        ),
    ]
