# Generated by Django 5.1 on 2024-09-09 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_vialocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vialocation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ride',
            name='return_drop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='return_drop_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='return_pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='return_pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnViaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_lat', models.FloatField()),
                ('via_lng', models.FloatField()),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_via_locations', to='dispatch.ride')),
            ],
        ),
    ]
