# Generated by Django 5.1 on 2024-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_remove_vialocation_created_at_ride_return_drop_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_return_vialocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_vialocation',
            field=models.BooleanField(default=False),
        ),
    ]
