# Generated by Django 5.1 on 2024-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_ride_is_return_vialocation_ride_is_vialocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='someone_else',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('someone_name', models.CharField(max_length=100)),
                ('someone_mobile_number', models.CharField(max_length=100)),
                ('someone_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='carry_on_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='discount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_off_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='email',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='landing_flight_number',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ride',
            name='mobile_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='outbound_meet_and_greet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='outbound_vehicle',
            field=models.CharField(choices=[('1', 'Executive Estate'), ('2', 'Executive Saloon (Sedan)'), ('3', 'Executive MPV')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='require_child_seat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='return_meet_and_greet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='return_vehicle',
            field=models.CharField(choices=[('1', 'Executive Estate'), ('2', 'Executive Saloon (Sedan)'), ('3', 'Executive MPV')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='suitcases_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
