# Generated by Django 5.1 on 2024-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_someone_else_ride_carry_on_capacity_ride_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='outbound_vehicle',
            field=models.CharField(choices=[('Executive Estate', '1'), ('2', 'Executive Saloon (Sedan)'), ('3', 'Executive MPV')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='return_vehicle',
            field=models.CharField(choices=[('Executive Estate', '1'), ('2', 'Executive Saloon (Sedan)'), ('3', 'Executive MPV')], max_length=100),
        ),
    ]
