# Generated by Django 5.1 on 2024-09-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_someone_else_ride'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='someone_else',
            new_name='SomeoneElse',
        ),
    ]
