# Generated by Django 5.1 on 2024-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_category',
            field=models.CharField(default='local Admin', max_length=100),
        ),
    ]
