# Generated by Django 5.1 on 2024-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='driver_files/')),
                ('status', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='other', max_length=100)),
                ('is_aprovedby', models.CharField(max_length=100, null=True)),
                ('is_createdby', models.CharField(max_length=100, null=True)),
                ('is_updatedby', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
