# Generated by Django 5.1 on 2024-09-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_files', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfile',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drivers.driver'),
        ),
    ]
