# Generated by Django 5.1 on 2024-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_files', '0003_alter_driverfile_is_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverfile',
            name='is_createdby',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
