# Generated by Django 5.1 on 2024-09-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_files', '0004_alter_driverfile_is_createdby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverfile',
            old_name='driver',
            new_name='driver_id',
        ),
    ]
