# Generated by Django 5.1 on 2024-09-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_files', '0005_rename_driver_driverfile_driver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverfile',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
