# Generated by Django 5.1 on 2024-09-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_number', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('company_vat_number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_vat_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company'),
        ),
    ]
