# Generated by Django 5.1 on 2024-09-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_company_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(default=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
