# Generated by Django 5.1 on 2024-09-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_alter_vehicle_vehicle_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_setting',
            fields=[
                ('booking_setting_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('booking_reference_number', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, default=None, max_length=10)),
                ('Fixed_prices_priority', models.CharField(blank=True, default='Zones', max_length=100)),
                ('Remove_decimal_zeros_from_price', models.BooleanField(blank=True, default=False)),
                ('Enable_booking_price_breakdown', models.BooleanField(blank=True, default=False)),
                ('Auto_delete_incomplete_bookings_after', models.BooleanField(blank=True, default=False)),
                ('Min_booking_time', models.TimeField(blank=True, default=None)),
                ('Enable_booking_cancellation', models.BooleanField(blank=True, default=False)),
                ('auto_refresh', models.BooleanField(blank=True, default=False)),
                ('refresh_time', models.TimeField(blank=True, null=True)),
                ('time_counter', models.BooleanField(default=True)),
                ('is_enable_meeting_board', models.BooleanField(default=True)),
                ('name_font_size', models.CharField(choices=[('1', 'small'), ('2', 'medium'), ('3', 'large')], max_length=1)),
                ('show_company_logo', models.CharField(max_length=1)),
                ('show_in_contents', models.CharField(max_length=1)),
                ('show_in_folder', models.CharField(max_length=1)),
                ('currency_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.currency')),
            ],
        ),
    ]
