# Generated by Django 5.1 on 2024-09-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_setting',
            name='currency_fk',
        ),
    ]
