# Generated by Django 5.1 on 2024-09-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_configuration', '0002_remove_booking_setting_currency_fk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking_setting',
            new_name='BookingSetting',
        ),
    ]
