# Generated by Django 5.1 on 2024-09-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_driver_is_createby_driver_is_updateby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Types',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicles_Types_name', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('display_type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('vehicle_custom_image', models.FileField(upload_to='image/vehicles_custom')),
                ('passengers', models.IntegerField()),
                ('luggage', models.IntegerField()),
                ('hand_luggage', models.IntegerField()),
                ('wheelchair', models.IntegerField()),
                ('booster_seats', models.IntegerField()),
                ('child_seats', models.IntegerField()),
                ('infant_seats', models.IntegerField()),
                ('ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_image', models.FileField(upload_to='image/vehicles')),
                ('registration_mark', models.CharField(max_length=100)),
                ('MOT', models.DateField(auto_now_add=True)),
                ('MOT_expiry_date', models.DateField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=100)),
                ('passenger_capacity', models.IntegerField()),
                ('registered_keeper_name', models.CharField(max_length=100)),
                ('registered_keeper_address', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_createby', models.CharField(max_length=100)),
                ('is_updateby', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('vehicle_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicles_types')),
            ],
        ),
    ]
