# Generated by Django 5.1 on 2024-09-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles_types',
            old_name='vehicle_id',
            new_name='vehicle_types_id',
        ),
    ]
