# Generated by Django 5.1 on 2024-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_vehicle_id_vehicles_types_vehicle_types_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles_types',
            name='vehicle_types_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
