# Generated by Django 5.1 on 2024-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_delete_users_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_createby',
            field=models.CharField(default=False),
        ),
    ]
