# Generated by Django 5.1 on 2024-09-02 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_updateby_user_language_user_last_login_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
