# Generated by Django 5.1 on 2024-08-22 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0009_rename_user_id_driver_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='driver_files/')),
                ('status', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='other', max_length=100)),
                ('is_aprovedby', models.CharField(max_length=100, null=True)),
                ('is_createdby', models.CharField(max_length=100, null=True)),
                ('is_updatedby', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drivers.driver')),
            ],
        ),
    ]
