# Generated by Django 5.1 on 2024-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetOperatores', '0002_alter_fleetoparetore_fleet_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetoparetore',
            name='operatore_id',
            field=models.CharField(default=False, unique=True),
        ),
    ]
