# Generated by Django 5.1 on 2024-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetOperatores', '0003_fleetoparetore_operatore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetoparetore',
            name='driver_id',
            field=models.CharField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fleetoparetore',
            name='operatore_id',
            field=models.CharField(default=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
