# Generated by Django 5.1 on 2024-08-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetOperatores', '0004_alter_fleetoparetore_driver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetoparetore',
            name='driver_id',
        ),
    ]
