# Generated by Django 5.1 on 2024-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
