# Generated by Django 5.1 on 2024-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('passengers', '0002_remove_passenger_id_alter_passenger_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='groups',
            field=models.ManyToManyField(related_name='passenger_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user_permissions',
            field=models.ManyToManyField(related_name='passenger_permissions', to='auth.permission'),
        ),
    ]
