# Generated by Django 5.1 on 2024-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_alter_passenger_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='timezone',
            field=models.CharField(default='UTC', max_length=63),
        ),
    ]
