# Generated by Django 5.1 on 2024-08-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_passenger_created_at_passenger_delete_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='delete_customer',
            new_name='delete_passenger',
        ),
    ]
