# Generated by Django 5.1 on 2024-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0006_rename_delete_customer_passenger_delete_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='requirment',
            field=models.CharField(default='pickup', max_length=100),
        ),
    ]
