# Generated by Django 5.1 on 2024-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='user_id',
            field=models.IntegerField(default=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
