# Generated by Django 5.1 on 2024-08-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_id_alter_driver_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='windwos_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
