# Generated by Django 5.1 on 2024-08-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_windwos_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='windwos_date',
        ),
    ]
