# Generated by Django 5.1 on 2024-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driver_windwos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='delete_users',
            field=models.BooleanField(default=False),
        ),
    ]
