# Generated by Django 5.1 on 2024-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driver_status_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='user_id',
            field=models.CharField(default=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
