# Generated by Django 5.1 on 2024-08-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_driver_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user_id',
            new_name='driver_id',
        ),
    ]
