# Generated by Django 5.1 on 2024-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('drivers', '0009_rename_user_id_driver_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='driver_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='driver_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
