# Generated by Django 5.1 on 2024-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetOparetore',
            fields=[
                ('oparetore_id', models.CharField(default=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('status_request', models.CharField(default='none', max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('telephone_number', models.IntegerField(null=True)),
                ('emergencey_number', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_number', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(max_length=500, null=True)),
                ('copany_vat_number', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(max_length=100, null=True)),
                ('fleet_income', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_oparetore', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('groups', models.ManyToManyField(related_name='oparetore_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='oparetore_permissions', to='auth.permission')),
            ],
        ),
    ]
